Document: nx-software-updater
Title: Debian nx-software-updater Manual
Author: <insert document author here>
Abstract: This manual describes what nx-software-updater is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/nx-software-updater/nx-software-updater.sgml.gz

Format: postscript
Files: /usr/share/doc/nx-software-updater/nx-software-updater.ps.gz

Format: text
Files: /usr/share/doc/nx-software-updater/nx-software-updater.text.gz

Format: HTML
Index: /usr/share/doc/nx-software-updater/html/index.html
Files: /usr/share/doc/nx-software-updater/html/*.html
